package com.locust.app

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.lifecycle.viewmodel.compose.viewModel
import kotlinx.coroutines.delay

private val Bg=Color(0xFF08090F);private val Surface=Color(0xFF11131D);private val Text=Color(0xFFE9E8F4);private val Muted=Color(0xFF858B9F);private val Iris=Color(0xFF9C8CFF)
class MainActivity:ComponentActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);setContent{MaterialTheme(colorScheme=darkColorScheme(background=Bg,surface=Surface,primary=Iris,onBackground=Text,onSurface=Text,onSurfaceVariant=Muted)){Locust()}}}}
@Composable fun Locust(vm:LocustVm=viewModel()){var tab by remember{mutableStateOf(0)};var story by remember{mutableStateOf<String?>(null)};var chapter by remember{mutableStateOf<String?>(null)};when{chapter!=null->Editor(vm,chapter!!){chapter=null};story!=null->Story(vm,story!!,{story=null},{chapter=it});else->Scaffold(containerColor=Bg,bottomBar={NavigationBar(containerColor=Surface){NavigationBarItem(tab==0,{tab=0},{},{Text("Library")});NavigationBarItem(tab==1,{tab=1},{},{Text("Desk")});NavigationBarItem(tab==2,{tab=2},{},{Text("Profile")})}}){p->Box(Modifier.padding(p)){when(tab){0->Library(vm){story=it};1->Desk(vm){story=it};2->Profile(vm)}}}}}
@Composable fun Header(a:String,b:String){Column(Modifier.padding(18.dp)){Text(a,27.sp,FontWeight.Bold);Text(b,color=Muted,fontSize=14.sp)}}
@Composable fun Library(vm:LocustVm,open:(String)->Unit){val xs by vm.stories.collectAsState();Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState())){Header("Library","Everything you're carrying");Button({vm.newStory(open)},Modifier.fillMaxWidth().padding(horizontal=18.dp)){Text("+  New story")};Spacer(Modifier.height(14.dp));xs.forEach{s->Card({open(s.id)},Modifier.fillMaxWidth().padding(7.dp,5.dp,7.dp),colors=CardDefaults.cardColors(Surface)){Column(Modifier.padding(16.dp)){Text(s.title.ifBlank{"Untitled story"},fontSize=19.sp,fontWeight=FontWeight.SemiBold);Text(s.category,color=Iris,fontSize=12.sp);if(s.description.isNotBlank())Text(s.description,color=Muted)}}}}}}
@Composable fun Story(vm:LocustVm,id:String,close:()->Unit,edit:(String)->Unit){val s by produceState<Story?>(null,id){value=vm.story(id)};val cs by vm.chapters(id).collectAsState();Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState())){Text("‹  Story",Modifier.padding(18.dp),fontSize=20.sp,fontWeight=FontWeight.Bold);s?.let{x->Column(Modifier.padding(horizontal=18.dp)){Text(x.title.ifBlank{"Untitled story"},fontSize=30.sp,fontWeight=FontWeight.Bold);Text(x.category,color=Iris);Spacer(Modifier.height(10.dp));Text(x.description.ifBlank{"No description yet."},color=Muted);Spacer(Modifier.height(20.dp));Text("Chapters",fontSize=17.sp,fontWeight=FontWeight.SemiBold);cs.forEach{c->Card({edit(c.id)},Modifier.fillMaxWidth().padding(vertical=5.dp),colors=CardDefaults.cardColors(Surface)){Column(Modifier.padding(15.dp)){Text(c.title,fontWeight=FontWeight.SemiBold);Text("${words(c.body)} words",color=Muted,fontSize=12.sp)}}}}}}}
@Composable fun Editor(vm:LocustVm,id:String,close:()->Unit){val c by produceState<Chapter?>(null,id){value=vm.chapter(id)};var title by remember(id){mutableStateOf("")};var body by remember(id){mutableStateOf("")};var ready by remember(id){mutableStateOf(false)};LaunchedEffect(c){if(c!=null&&!ready){title=c!!.title;body=c!!.body;ready=true}};LaunchedEffect(title,body,ready){if(ready&&c!=null){delay(500);vm.save(c!!.copy(title=title,body=body))}};Column(Modifier.fillMaxSize().background(Bg)){Text("×   Writing     ${words(body)} words",Modifier.padding(16.dp),fontSize=18.sp,fontWeight=FontWeight.Bold);BasicTextField(title,{title=it},Modifier.fillMaxWidth().padding(20.dp),textStyle=TextStyle(Text,25.sp,FontWeight.Bold));BasicTextField(body,{body=it},Modifier.fillMaxSize().padding(horizontal=20.dp),textStyle=TextStyle(Text,18.sp,lineHeight=29.sp))}}
@Composable fun Desk(vm:LocustVm,open:(String)->Unit){val xs by vm.stories.collectAsState();Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState())){Header("Desk","Everything you're carrying");Card(Modifier.fillMaxWidth().padding(18.dp),colors=CardDefaults.cardColors(Surface)){Column(Modifier.padding(18.dp)){Text("Continue writing",fontSize=19.sp,fontWeight=FontWeight.SemiBold);val x=xs.maxByOrNull{it.updatedAt};Text(x?.title?.ifBlank{"Untitled story"}?:"Nothing to continue yet",color=Muted);if(x!=null)Button({open(x.id)}){Text("Continue")}}}}}
@Composable fun Profile(vm:LocustVm){val p by vm.profile.collectAsState();var name by remember(p?.name){mutableStateOf(p?.name?:"")};var handle by remember(p?.handle){mutableStateOf(p?.handle?:"")};var about by remember(p?.about){mutableStateOf(p?.about?:"")};Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState())){Header("Profile","Yours, and only on this device");Card(Modifier.fillMaxWidth().padding(18.dp),colors=CardDefaults.cardColors(Surface)){Column(Modifier.padding(18.dp)){Text("Your pen name",color=Muted);OutlinedTextField(name,{name=it;vm.save((p?:Profile()).copy(name=it))},Modifier.fillMaxWidth());Text("Handle",color=Muted);OutlinedTextField(handle,{handle=it;vm.save((p?:Profile()).copy(handle=it))},Modifier.fillMaxWidth());Text("About me",color=Muted);OutlinedTextField(about,{about=it;vm.save((p?:Profile()).copy(about=it))},Modifier.fillMaxWidth(),minLines=3);Spacer(Modifier.height(12.dp));Text("Local storage",fontSize=18.sp,fontWeight=FontWeight.SemiBold);Text("Your writing is stored in Locust's native SQLite database. No broad storage permission is required.",color=Muted)}}}}
fun words(s:String)=s.trim().split(Regex("\\s+")).count{it.isNotBlank()}
